version: "3.8"

services:   
    keycloak:
        build: .
        image: aguirresabino/keycloak
        container_name: keycloak
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_ADDR=db
            - DB_VENDOR=postgres
            - DB_DATABASE=keycloak
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=postgres
        ports:
            - 8080:8080
        depends_on:
            - db
        networks:
            - keycloak
    
    db:
        restart: always
        image: "postgres:alpine"
        container_name: "keycloak-db"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=keycloak
        volumes:
            - ./.docker/dbdata:/var/lib/postgresql/data
        tty: true
        networks:
            - keycloak
            
networks:
    keycloak: 